{
    "sites": [
        {
            "key": "drpy_js_å¥‡çå¼‚å…½",
            "name": "ğŸ’–â˜…é”¦å“¥å½±è§†â˜…å…«å®å‘¨ï¼ˆä¸€ä¸–ç‰ç’ƒâ˜…è®¸ä½ ä¸‰ä¸–æƒ…ç¼˜ï¼‰",
            "type": 3,
            "api": "http://alist.xn--z7x900a.love:63/drpy2.min.js",
            "ext": "https://pan.shangui.cc/f/QeEVFm/aiqiyi.js"
        },
        {
            "key": "csp_SP360",
            "name": "ğŸ’–â˜…é”¦å“¥èšåˆâ˜…",
            "type": 3,
            "api": "csp_XBPQ",
            "searchable": 1,
            "quickSearch": 1,
            "filterable": 1,
            "ext": "https://pan.shangui.cc/f/Xnz5Fd/360.js"
        },
        {
            "key": "csp_xml_å§é¾™èµ„æº",
            "name": "ğŸ’–â˜…é”¦å“¥èµ„æºâ˜…",
            "type": 1,
            "api": "https://collect.wolongzyw.com/api.php/provide/vod/",
            "playUrl": "",
            "searchable": 1,
            "quickSearch": 1
        },
        {
            "key": "YQK_spider",
            "name": "ğŸ’–â˜…é”¦å“¥å½±é™¢â˜…",
            "api": "csp_YQKAPP",
            "type": 3,
            "filterable": 1,
            "playerType": 2,
            "quickSearch": 1,
            "searchable": 1,
            "ext": "https://hk-api-cf.yqk5659.com"
        },
        {
            "key": "csp_CZSPP",
            "name": "ğŸ­â˜…çˆ±å¥‡è‰ºæºâ˜…",
            "type": 3,
            "api": "csp_Czsapp",
            "searchable": 1,
            "quickSearch": 1,
            "filterable": 1
        },
        {
			"key":"drpy_js_ä¼˜é…·1",
			"name":"ğŸ‘‘â˜…ä¼˜é…·è§†é¢‘â˜…",
			"type":3,
			"api":"https://agit.ai/Yemaozhi123/yemao/raw/branch/master/lib/drpy2.min.js",
			"ext":"https://pan.shangui.cc/f/Xnzyfd/youku.js"
		},
        {
            "key": "Qtv",
            "name": "ğŸ§â˜…è…¾è®¯è§†é¢‘â˜…",
            "type": 3,
            "api": "csp_Qtv",
            "searchable": 1,
            "quickSearch": 1,
            "filterable": 1
        },
        {
            "key": "MGT",
            "name": "ğŸ‹â˜…èŠ’æœè§†é¢‘â˜…",
            "type": 3,
            "api": "csp_Mtv",
            "searchable": 1,
            "quickSearch": 1,
            "filterable": 1
        },
        {
            "key": "Kuaikan",
            "name": "ğŸ‘€â˜…å¿«çœ‹å½±è§†â˜…",
            "type": 3,
            "api": "csp_Kuaikan",
            "searchable": 1,
            "quickSearch": 1,
            "filterable": 1
        },
        {
            "key": "csp_search_Alips",
            "name": "ğŸ¦Œâ˜…é”¦å“¥æœç´¢â˜…",
            "type": 3,
            "api": "csp_PanSou",
            "playerType": 1,
            "searchable": 1,
            "quickSearch": 1,
            "filterable": 0,
            "ext": "http://127.0.0.1:9978/file/fatcat/token.txt"
        },
        {
            "key": "csp_search_PanSearch",
            "name": "ğŸ—‚ï¸â˜…ç›˜æœæœç´¢â˜…",
            "type": 3,
            "api": "csp_PanSearch",
            "searchable": 1,
            "quickSearch": 1,
            "filterable": 0,
            "ext": "http://127.0.0.1:9978/file/fatcat/token.txt"
        },
        {
            "key": "csp_search_Upyunso",
            "name": "ğŸâ˜…äº‘æœèµ„æºâ˜…",
            "type": 3,
            "api": "csp_UpYun",
            "playerType": 1,
            "searchable": 1,
            "quickSearch": 1,
            "filterable": 0,
            "ext": "http://127.0.0.1:9978/file/fatcat/token.txt"
        },
        {
            "key": "å„¿ç«¥",
            "name": "ğŸ“šâ˜…å„¿ç«¥å¯è’™â˜…",
            "type": 3,
            "api": "csp_Bili",
            "searchable": 1,
            "quickSearch": 1,
            "filterable": 1,
            "ext": "http://52bsj.vip:81/api/v3/file/get/61578/%E5%B0%91%E5%84%BF%E6%95%99%E8%82%B2.json?sign=3BlFTWj-rXJPPgJB6eQ1_C0odRnDCaW28cr8afXaO_I%3D%3A0"
        },
        {
            "key": "å°å­¦",
            "name": "ğŸ“šâ˜…å°å­¦åŒæ­¥â˜…",
            "type": 3,
            "api": "csp_Bili",
            "searchable": 1,
            "quickSearch": 1,
            "filterable": 1,
            "ext": "http://52bsj.vip:81/api/v3/file/get/61579/%E5%B0%8F%E5%AD%A6%E8%AF%BE%E5%A0%82.json?sign=Oqbf9547dxbhVTf07kdHsuNZgzIWH2UT9uY7zRbTA5M%3D%3A0"
        },
        {
            "key": "åˆä¸­",
            "name": "ğŸ“šâ˜…åˆä¸­åŒæ­¥â˜…",
            "type": 3,
            "api": "csp_Bili",
            "searchable": 1,
            "quickSearch": 1,
            "filterable": 1,
            "ext": "http://52bsj.vip:81/api/v3/file/get/61581/%E5%88%9D%E4%B8%AD%E8%AF%BE%E5%A0%82.json?sign=7Jxqd0BzuIm-2OvXZyoRasDb1P3OojENYkxLf6bhLr0%3D%3A0"
        },
        {
            "key": "é«˜ä¸­",
            "name": "ğŸ“šâ˜…é«˜ä¸­åŒæ­¥â˜…",
            "type": 3,
            "api": "csp_Bili",
            "searchable": 1,
            "quickSearch": 1,
            "filterable": 1,
            "ext": "http://52bsj.vip:81/api/v3/file/get/61580/%E9%AB%98%E4%B8%AD%E8%AF%BE%E5%A0%82.json?sign=ESNTJf_EMO0ch_J5j-kV35jFLeg1GvG4VJjUqW2DJCc%3D%3A0"
        },
        {
            "key": "csp_FanYY",
            "name": "â˜…å¤©ä¸Šç™½ç‰äº¬â˜…",
            "type": 3,
            "api": "csp_WoGG",
            "searchable": 1,
            "quickSearch": 1,
            "filterable": 1,
            "ext": "http://127.0.0.1:9978/file/fatcat/token.txt$$$https://wogg.xyz/"
        },
        {
            "key": "csp_77",
            "name": "â˜…åäºŒæ¥¼äº”åŸâ˜…",
            "type": 3,
            "api": "csp_Kunyu77",
            "searchable": 1,
            "quickSearch": 1,
            "filterable": 1,
            "jar": "https://files.zohopublic.com.cn/public/workdrive-public/download/uyv0t678c488189af47bb91dc108484d17431",
            "changeable": 1
        },
        {
            "key": "csp_AppMr",
            "name": "â˜…ä»™äººæŠšæˆ‘é¡¶â˜…",
            "type": 3,
            "api": "csp_AppMr",
            "searchable": 1,
            "quickSearch": 1,
            "filterable": 1
        },
        {
            "key": "csp_xml_ck",
            "name": "â˜…ç»“å‘æˆé•¿ç”Ÿâ˜…",
            "type": 0,
            "api": "https://ckzy.me/api.php/provide/vod/at/xml/",
            "searchable": 1,
            "quickSearch": 1,
            "filterable": 0,
            "categories": [
                "ä¼¦ç†ç‰‡",
                "åŠ¨ä½œç‰‡",
                "å–œå‰§ç‰‡",
                "çˆ±æƒ…ç‰‡",
                "ç§‘å¹»ç‰‡",
                "ææ€–ç‰‡",
                "å‰§æƒ…ç‰‡",
                "æˆ˜äº‰ç‰‡",
                "æ‚¬ç–‘ç‰‡",
                "è®°å½•ç‰‡",
                "çŠ¯ç½ªç‰‡",
                "å¥‡å¹»ç‰‡",
                "ç”µè§†å‰§",
                "å›½äº§å‰§",
                "æ¬§ç¾å‰§",
                "æ—¥éŸ©å‰§",
                "æ¸¯å°å‰§"
            ]
        },
        {
            "key": "æ¼”å”±ä¼š",
            "name": "ğŸ…±â˜…ç ´ç«™éŸ³ä¹â˜…",
            "type": 3,
            "api": "csp_Bili",
            "searchable": 1,
            "quickSearch": 0,
            "filterable": 1,
            "ext": "https://pan.shangui.cc/f/XnXqFd/yinyue.js"
        },
        {
            "key": "csp_æˆæ›²",
            "name": "ğŸ…±â˜…ç ´ç«™æˆæ›²â˜…",
            "type": 3,
            "api": "csp_Bili",
            "searchable": 1,
            "quickSearch": 0,
            "filterable": 1,
            "ext": "https://pan.shangui.cc/f/8VzpHo/xiqu.js"
        },
        {
            "key": "ğŸ”¥å…‰é€Ÿèµ„æº",
            "name": "å¾®ä¿¡å…¬ä¼—å·:ä¸€ä¸–ç‰ç’ƒè®¸ä½ ä¸‰ä¸–æƒ…ç¼˜",
            "type": 1,
            "api": "https://api.guangsuapi.com/api.php/provide/vod/",
            "searchable": 1,
            "quickSearch": 1,
            "filterable": 0
        },
        {
            "key":"drpy_js_é”¦å“¥",
            "name":"é”¦å“¥å½±è§†åº”æœ‰å°½æœ‰",
            "type":3,
            "api":"https://cdn.jsdelivr.net/gh/yxcqr/DZDRPY@main/libs/drpy.min.js",
            "ext":"https://cdn.jsdelivr.net/gh/yxcqr/DZDRPY@main/js/èœç‹—.js"
        }
    ],
    "lives": [
    {
      "group": "IPTV",
      "channels": [
        {
          "name": "é”¦å“¥ç›´æ’­",
          "urls": [
            "proxy://do=live&type=txt&ext=aHR0cDovL3BhbmRvd24ucHJvL3R2Ym94L3poaWJvLnR4dA=="
          ]
        }
      ]
    }
  ],
    "parses": [
        {
            "name": "è‡ªåŠ¨",
            "type": 3,
            "url": "Demo"
        },
        {
            "name": "æ‰‹åŠ¨",
            "type": 3,
            "url": "Web"
        },
        {
            "name": "é”¦å“¥è§£æ",
            "type": 1,
            "url": "http://27.124.4.42:4567/jhjson/ceshi.php?url="
        },
        {
            "name": "é”¦å“¥è§£æ",
            "type": 1,
            "url": "http://110.42.2.247:880/analysis/json/?uid=2449&my=acfgikquvzFGJRW459&url="
        },
        {
            "name": "é”¦å“¥è§£æ",
            "type": 1,
            "url": "https://jx.ccabc.cc/xc/?key=5567332json&url="
        },
        {
            "name": "é”¦å“¥è§£æ",
            "type": 1,
            "url": "http://27.124.4.42:4567/jhjson/ceshi.php?url="
        },
        {
            "name": "ä¸€ä¸–ç‰ç’ƒ",
            "type": 1,
            "url": "http://jx.fuqizhishi.com:63/æ¥å£åœ°å€www.è‚¥çŒ«.love/è‚¥çŒ«ä¸“ç”¨.php?url="
        },
        {
            "name": "è®¸",
            "type": 2,
            "url": "Sequence"
        },
        {
            "name": "ä½ ",
            "type": 2,
            "url": "Parallel"
        },
        {
            "name": "ä¸‰ä¸–æƒ…ç¼˜",
            "type": 1,
            "url": "http://27.124.4.42:4567/jhjson/ceshi.php?url="
        },
    {
      "name": "æˆ‘",
      "type": 1,
      "url": "http://27.124.4.42:4567/jhjson/ceshi.php?url="
    },
    {
      "name": "å‘½",
      "type": 1,
      "url": "http://110.42.2.247:880/analysis/json/?uid=2449&my=acfgikquvzFGJRW459&url="
    },
    {
      "name": "ç”±",
      "type": 1,
      "url": "http://27.124.4.42:4567/jhjson/ceshi.php?url="
    },
    {
      "name": "æˆ‘",
      "type": 1,
      "url": "https://json.key521.cn/api/?key=df27d9ca9ec97e22c47f8565a50aa6f5&url="
    },
    {
      "name": "ä¸",
      "type": 1,
      "url": "http://27.124.4.42:4567/jhjson/ceshi.php?url="
    },
    {
      "name": "ç”±",
      "type": 1,
      "url": "http://json.84jia.com/home/api?type=ys&uid=335253&key=fjklpqsyCDGMNQRWX8&url="
    },
        {
"name": "å¤©",
"type": 1,
"url": "http://xhww.fun:63/å°ç±³ç‰¹åˆ«çˆ±è‚¥çŒ«.php?url=",
"ext": {
"flag": ["qq", "è…¾è®¯", "qiyi", "çˆ±å¥‡è‰º", "å¥‡è‰º", "youku", "ä¼˜é…·", "sohu", "æœç‹", "letv", "ä¹è§†", "mgtv", "èŠ’æœ", "CL4K", "renrenmi", "ltnb", "bilibili", "1905", "xigua", "nongmin", "CL4K", "xfyun", "ffm3u8", "lzm3u8", "netease", "pgyer","TD", "qzone", "FY", "ppayun", "Feiyun", "zhibo"],
"header": {
"User-Agent": "Dalvik/2.1.0 (Linux; U; Android 10; PDHM00 Build/QKQ1.191222.002)"

}
}}
    ],
    "rules": [
        {
            "host": "*",
            "rule": [
                "default.365yg.com"
            ]
        },
        {
            "host": "dyxs20.com",
            "rule": [
                ".m3u8"
            ]
        },
        {
            "host": "www.agemys.cc",
            "rule": [
                "cdn-tos",
                "obj/tos-cn"
            ]
        },
        {
            "host": "www.sharenice.net",
            "rule": [
                "http.*?/play.{0,3}\\?[^url]{2,8}=.*"
            ]
        },
        {
            "host": "www.sharenice.net",
            "rule": [
                "qianpailive.com",
                "vid="
            ]
        },
        {
            "host": "*",
            "rule": [
                "douyin.com/aweme",
                "video_id="
            ]
        },
        {
            "host": "*",
            "rule": [
                "huoshan.com",
                "/item/video/"
            ]
        },
        {
            "host": "*",
            "rule": [
                "http((?!http).){12,}?\\.(m3u8|mp4|flv|avi|mkv|rm|wmv|mpg|m4a)\\?.*"
            ]
        },
        {
            "host": "*",
            "rule": [
                "http((?!http).){12,}\\.(m3u8|mp4|flv|avi|mkv|rm|wmv|mpg|m4a)"
            ]
        }
    ],
    "flags": [
        "youku",
        "ä¼˜é…·",
        "ä¼˜ é…·",
        "ä¼˜é…·è§†é¢‘",
        "qq",
        "è…¾è®¯",
        "è…¾ è®¯",
        "è…¾è®¯è§†é¢‘",
        "iqiyi",
        "qiyi",
        "å¥‡è‰º",
        "çˆ±å¥‡è‰º",
        "çˆ± å¥‡ è‰º",
        "m1905",
        "xigua",
        "letv",
        "leshi",
        "ä¹è§†",
        "ä¹ è§†",
        "sohu",
        "æœç‹",
        "æœ ç‹",
        "æœç‹è§†é¢‘",
        "tudou",
        "pptv",
        "mgtv",
        "èŠ’æœ",
        "imgo",
        "èŠ’æœTV",
        "èŠ’ æœ T V",
        "bilibili",
        "å“” å“©",
        "å“” å“© å“” å“©",
        "FY",
        "fy",
        "FeiYun",
        "feiyun",
        "é£äº‘"
    ],
    "ijk": [
        {
            "group": "è½¯è§£ç ",
            "options": [
                {
                    "category": 4,
                    "name": "opensles",
                    "value": "0"
                },
                {
                    "category": 4,
                    "name": "overlay-format",
                    "value": "842225234"
                },
                {
                    "category": 4,
                    "name": "framedrop",
                    "value": "1"
                },
                {
                    "category": 4,
                    "name": "soundtouch",
                    "value": "1"
                },
                {
                    "category": 4,
                    "name": "start-on-prepared",
                    "value": "1"
                },
                {
                    "category": 1,
                    "name": "http-detect-range-support",
                    "value": "0"
                },
                {
                    "category": 1,
                    "name": "fflags",
                    "value": "fastseek"
                },
                {
                    "category": 2,
                    "name": "skip_loop_filter",
                    "value": "48"
                },
                {
                    "category": 4,
                    "name": "reconnect",
                    "value": "1"
                },
                {
                    "category": 4,
                    "name": "max-buffer-size",
                    "value": "5242880"
                },
                {
                    "category": 4,
                    "name": "enable-accurate-seek",
                    "value": "0"
                },
                {
                    "category": 4,
                    "name": "mediacodec",
                    "value": "0"
                },
                {
                    "category": 4,
                    "name": "mediacodec-auto-rotate",
                    "value": "0"
                },
                {
                    "category": 4,
                    "name": "mediacodec-handle-resolution-change",
                    "value": "0"
                },
                {
                    "category": 4,
                    "name": "mediacodec-hevc",
                    "value": "0"
                },
                {
                    "category": 1,
                    "name": "dns_cache_timeout",
                    "value": "600000000"
                }
            ]
        },
        {
            "group": "ç¡¬è§£ç ",
            "options": [
                {
                    "category": 4,
                    "name": "opensles",
                    "value": "0"
                },
                {
                    "category": 4,
                    "name": "overlay-format",
                    "value": "842225234"
                },
                {
                    "category": 4,
                    "name": "framedrop",
                    "value": "1"
                },
                {
                    "category": 4,
                    "name": "soundtouch",
                    "value": "1"
                },
                {
                    "category": 4,
                    "name": "start-on-prepared",
                    "value": "1"
                },
                {
                    "category": 1,
                    "name": "http-detect-range-support",
                    "value": "0"
                },
                {
                    "category": 1,
                    "name": "fflags",
                    "value": "fastseek"
                },
                {
                    "category": 2,
                    "name": "skip_loop_filter",
                    "value": "48"
                },
                {
                    "category": 4,
                    "name": "reconnect",
                    "value": "1"
                },
                {
                    "category": 4,
                    "name": "max-buffer-size",
                    "value": "5242880"
                },
                {
                    "category": 4,
                    "name": "enable-accurate-seek",
                    "value": "0"
                },
                {
                    "category": 4,
                    "name": "mediacodec",
                    "value": "1"
                },
                {
                    "category": 4,
                    "name": "mediacodec-auto-rotate",
                    "value": "1"
                },
                {
                    "category": 4,
                    "name": "mediacodec-handle-resolution-change",
                    "value": "1"
                },
                {
                    "category": 4,
                    "name": "mediacodec-hevc",
                    "value": "1"
                },
                {
                    "category": 1,
                    "name": "dns_cache_timeout",
                    "value": "600000000"
                }
            ]
        }
    ],
    "ads": [
        "wan.51img1.com",
        "iqiyi.hbuioo.com",
        "vip.ffzyad.com",
        "https://lf1-cdn-tos.bytegoofy.com/obj/tos-cn-i-dy/455ccf9e8ae744378118e4bd289288dd"
    ],
    "wallpaper": "http://æˆ‘ä¸æ˜¯.è‚¥çŒ«.love:63/pic/feimao.php",
    "warningText": "é”¦å“¥å½±è§†ï¼Œç»™ä½ ä¸ä¸€æ ·çš„å½±è§†è§†ç•Œï¼Œä½ æƒ³è¦çš„ï¼Œç»Ÿç»Ÿéƒ½æœ‰ï¼",
    "spider": "http://æˆ‘ä¸æ˜¯.è‚¥çŒ«.love:63/Jar/pandaQ230714.jar;md5;620bec58d59eb55110ca4d731ce736ae",
    "spider": "https://agit.ai/ddx/TVBox/raw/branch/master/js/uyv0t678c488189af47bb91dc108484d17431;md5;f024a5e507951d3c20514202aa6cf5fe"
}
